### PR TITLE
add(vscode config): use local typescript library, and make file list …

### PR DESCRIPTION
**Pull request by zixia**
…view clean

### CODE REVIEW

**Comment by JIoJIaJIu** [comment]
@zixia I don't think that specific editor config files should be in the repo, can it be achieved with common configuration, for example with `tsconfig.json`?

**Comment by zixia** [comment]
@JIoJIaJIu This file contains setting for vscode, its functionality can not be achieved by `tsconfig.json` or other config files.

For example: 
1. `files.exclude` entry is to control which file/directory should be hidden in the Sidebar Explorer in vscode IDE.
1. `typescript.tsdk` will be used by vscode by static type checking service, and IntelliSense.
1. etc.

So my suggestion is to include it, to make the vscode IDE behavior consistent across the developer/computer.

**Comment by JIoJIaJIu** [comment]
Sorry, but I dont think that specific editor configuration should exist in the repo, better to store it locally

**Comment by zixia** [comment]
No problem. 

However, as we are using TypeScript, I'll strongly suggest you switch your IDE to vscode because it has the best support for TypeScript/JavaScript. :P

**Comment by JIoJIaJIu** [comment]
@zixia I installed it today - really awesome tool, will look it slowly

**Pull request closed without merging**
